name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get PR diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > pr.diff

      - name: Send diff to review API
        run: |
          curl -X POST http://localhost:3001/api/code/review \
            -H "Authorization: Bearer ${{ secrets.REVIEW_BOT_TOKEN }}" \
            -H "Content-Type: text/plain" \
            --data-binary @pr.diff
        env:
          GITHUB_PR_TOKEN: ${{ secrets.GITHUB_TOKEN }}